version: '3.8'

services:
  bitcoind:
    image: kylemanna/bitcoind
    #command: ["bitcoind", "-testnet4"]
    volumes:
      - bitcoind-data:/bitcoin/.bitcoin
      - ./bitcoind/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    ports:
      - 8333:8333
      - 127.0.0.1:8332:8332
    networks:
      - bitcoin_network   
  # electrs:
  #   image: electrs:
  #   depends_on:
  #     - bitcoind
  #   build:
  #     image: mempool/electrs         
  #   restart: on-failure
  #   networks:
  #     default:
  #       ipv4_address: 172.18.0.5

volumes:
  bitcoin_data:

networks:
  bitcoin_network: