version: '3.8'

services:
  bitcoind:
    image: kylemanna/bitcoind    
    volumes:
      - bitcoind-data:/bitcoin/.bitcoin
      - ./bitcoind/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf      
    ports:
      - 8333:8333
      - 8332:8332
    networks:
      - bitcoin_network   
  electrs:
    image: mempool/electrs         
    depends_on:
      - bitcoind    
    restart: on-failure
    ports:
      - 50001:50001
    networks:
      - bitcoin_network     
    volumes:
      - electrs_data:/electrs
      - bitcoind-data:/root/.bitcoin:ro
      - ./config.toml:/config.toml:ro
    entrypoint:
      -  /bin/electrs
    command: |
      --conf /config.toml

volumes:
  bitcoind-data:
  electrs_data:

networks:
  bitcoin_network:
    driver: bridge